import React from "react"
import Layout from "../components/layout"
import SEO from "../components/seo"
import { StaticImage } from "gatsby-plugin-image"

const Terms = () => (
  <Layout>
    <SEO title="Advertise with Bigindia.com" />
    <div className="text-gray-700 body-font">
      <div className="flex p-8 md:flex-row flex-col">
        <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0">
          <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            TERMS OF USE
          </h1>
          <p className="mb-5 leading-relaxed">
            PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS
            WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO BE BOUND
            BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">General</p>

          <p className="mb-5 leading-relaxed">
            This document is an electronic record in terms of The Information
            Technology Act, 2000 ("IT Act") and rules there under, and is
            published in accordance with the provisions of Rule 3 (1) of the
            Information Technology (Intermediaries Guidelines) Rules 2011, which
            mandates for publishing of rules and regulations, privacy policy and
            terms of use for access or usage of the Website. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures. For details
            -https://www.meity.gov.in/content/information-technology-act-2000
          </p>

          <p className="mb-5 leading-relaxed">
            This Terms of Service Agreement governs your use of this website,
            BigIndia.com, BigIndia.com offer of products for purchase on this
            Website, or your purchase of products available on this Website.
            This Agreement includes, and incorporates by this reference, the
            policies and guidelines referenced below. BigIndia.com reserves the
            right to change or revise the terms and conditions of this Agreement
            at any time by posting any changes or a revised Agreement on this
            Website. The changed or revised Agreement will be effective
            immediately after it is posted on this Website. Your use of the
            Website following the posting any such changes or of a revised
            Agreement will constitute your acceptance of any such changes or
            revisions. BigIndia.com encourages you to review this Agreement
            whenever you visit the Website to make sure that you understand the
            terms and conditions governing use of the Website. This Agreement
            does not alter in any way the terms or conditions of any other
            written agreement you may have with BigIndia.com for other products
            or services. If you do not agree to this Agreement (including any
            referenced policies or guidelines), please immediately terminate
            your use of the Website. If you would like to print this Agreement,
            please click the print button on your browser toolbar.
          </p>

          <p className="mb-5 leading-relaxed text-xl font-semibold">
            I. PRODUCTS
          </p>

          <p className="mb-5 leading-relaxed font-semibold">Terms of Offer</p>

          <p className="mb-5 leading-relaxed">
            This Website offers for sale certain products. By placing an order
            for Products through this Website, you agree to the terms set forth
            in this Agreement.
          </p>

          <p className="mb-5 leading-relaxed">
            Customer Solicitation: Unless you notify our third party call center
            reps or direct BigIndia.com sales reps, while they are calling you,
            of your desire to opt out from further direct company communications
            and solicitations, you are agreeing to continue to receive further
            emails and call solicitations BigIndia.com and its designated in
            house or third party call team(s).
          </p>
          <p className="mb-5 leading-relaxed">
            Opt Out Procedure: We provide 3 easy ways to opt out of from future
            solicitations.
          </p>
          <p className="mb-5 leading-relaxed">
            1. You may use the opt out link found in any email solicitation that
            you may receive.{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            2. You may also choose to opt out, via sending your email address to
            our email.
          </p>
          <p className="mb-5 leading-relaxed">
            3. You may send a written remove request to Company Address.{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            Proprietary Rights
            <br />
            BigIndia.com has proprietary rights and trade secrets in the
            Products. You may not copy, reproduce, resell or redistribute any
            Product manufactured and/or distributed by BigIndia.com.
            BigIndia.com also has rights to all trademarks and trade dress and
            specific layouts of this webpage, including calls to action, text
            placement, images and other information.
          </p>
          <p className="mb-5 leading-relaxed">
            Sales Tax/GST
            <br />
            If you purchase any Products, you will be responsible for paying any
            applicable sales tax.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            II. WEBSITE
          </p>
          <p className="mb-5 leading-relaxed">
            Content; Intellectual Property; Third Party Links{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            In addition to making Products available, this Website also offers
            information and marketing materials. This Website also offers
            information, both directly and through indirect links to third-party
            websites, about nutritional and dietary supplements. BigIndia.com
            does not always create the information offered on this Website;
            instead the information is often gathered from other sources. To the
            extent that BigIndia.com does create the content on this Website,
            such content is protected by intellectual property laws of the
            India, foreign nations, and international bodies. Unauthorized use
            of the material may violate copyright, trademark, and/or other laws.
            You acknowledge that your use of the content on this Website is for
            personal, noncommercial use. Any links to third-party websites are
            provided solely as a convenience to you. BigIndia.com does not
            endorse the contents on any such third-party websites. BigIndia.com
            is not responsible for the content of or any damage that may result
            from your access to or reliance on these third-party websites. If
            you link to third-party websites, you do so at your own risk.{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            Use of Website; BigIndia.com is not responsible for any damages
            resulting from use of this website by anyone. You will not use the
            Website for illegal purposes. You will
          </p>
          <p className="mb-5 leading-relaxed">
            (1) abide by all applicable local, state, national, and
            international laws and regulations in your use of the Website
            (including laws regarding intellectual property),{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            (2) not interfere with or disrupt the use and enjoyment of the
            Website by other users,{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            (3) not resell material on the Website,{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            (4) not engage, directly or indirectly, in transmission of "spam",
            chain letters, junk mail or any other type of unsolicited
            communication, and{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            (5) not defame, harass, abuse, or disrupt other users of the Website
          </p>
          <p className="mb-5 leading-relaxed font-semibold">License</p>
          <p className="mb-5 leading-relaxed">
            By using this Website, you are granted a limited, non-exclusive,
            non-transferable right to use the content and materials on the
            Website in connection with your normal, noncommercial, use of the
            Website. You may not copy, reproduce, transmit, distribute, or
            create derivative works of such content or information without
            express written authorization from BigIndia.com or the applicable
            third party (if third party content is at issue).
          </p>
          <p className="mb-5 leading-relaxed font-semibold">Posting </p>
          <p className="mb-5 leading-relaxed">
            By posting, storing, or transmitting any content on the Website, you
            hereby grant BigIndia.com a perpetual, worldwide, non-exclusive,
            royalty-free, assignable, right and license to use, copy, display,
            perform, create derivative works from, distribute, have distributed,
            transmit and assign such content in any form, in all media now known
            or hereinafter created, anywhere in the world. BigIndia.com does not
            have the ability to control the nature of the user-generated content
            offered through the Website. You are solely responsible for your
            interactions with other users of the Website and any content you
            post. BigIndia.com is not liable for any damage or harm resulting
            from any posts by or interactions between users. BigIndia.com
            reserves the right, but has no obligation, to monitor interactions
            between and among users of the Website and to remove any content
            BigIndia.com deems objectionable, in sole discretion.{" "}
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            III. DISCLAIMER OF WARRANTIES
          </p>
          <p className="mb-5 leading-relaxed">
            YOUR USE OF THIS WEBSITE AND/OR PRODUCTS ARE AT YOUR SOLE RISK. THE
            WEBSITE AND PRODUCTS ARE OFFERED ON AN "AS IS" AND "AS AVAILABLE"
            BASIS. BigIndia.com EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
            WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED
            WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
            NON-INFRINGEMENT WITH RESPECT TO THE PRODUCTS OR WEBSITE CONTENT, OR
            ANY RELIANCE UPON OR USE OF THE WEBSITE CONTENT OR PRODUCTS.
            ("PRODUCTS" INCLUDE TRIAL PRODUCTS.)
          </p>
          <p className="mb-5 leading-relaxed">
            WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, BigIndia.com MAKES
            NO WARRANTY:
          </p>
          <p className="mb-5 leading-relaxed">
            THAT THE INFORMATION PROVIDED ON THIS WEBSITE IS ACCURATE, RELIABLE,
            COMPLETE, OR TIMELY.
          </p>
          <p className="mb-5 leading-relaxed">
            THAT THE LINKS TO THIRD-PARTY WEBSITES ARE TO INFORMATION THAT IS
            ACCURATE, RELIABLE, COMPLETE, OR TIMELY.
          </p>
          <p className="mb-5 leading-relaxed">
            NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU
            FROM THIS WEBSITE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED
            HEREIN.{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PRODUCTS
            OR THAT DEFECTS IN PRODUCTS WILL BE CORRECTED.{" "}
          </p>
          <p className="mb-5 leading-relaxed">
            REGARDING ANY PRODUCTS PURCHASED OR OBTAINED THROUGH THE WEBSITE.
          </p>
          <p className="mb-5 leading-relaxed">
            SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES,
            SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            IV. LIMITATION OF LIABILITY
          </p>
          <p className="mb-5 leading-relaxed">
            BigIndia.com ENTIRE LIABILITY, AND YOUR EXCLUSIVE REMEDY, IN LAW, IN
            EQUITY, OR OTHWERWISE, WITH RESPECT TO THE WEBSITE CONTENT AND
            PRODUCTS AND/OR FOR ANY BREACH OF THIS AGREEMENT IS SOLELY LIMITED
            TO THE AMOUNT YOU PAID, LESS SHIPPING AND HANDLING, FOR PRODUCTS
            PURCHASED VIA THE WEBSITE.
          </p>
          <p className="mb-5 leading-relaxed">
            BigIndia.com WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,
            INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH THIS
            AGREEMENT OR THE PRODUCTS IN ANY MANNER, INCLUDING LIABILITIES
            RESULTING FROM (1) THE USE OR THE INABILITY TO USE THE WEBSITE
            CONTENT OR PRODUCTS; (2) THE COST OF PROCURING SUBSTITUTE PRODUCTS
            OR CONTENT; (3) ANY PRODUCTS PURCHASED OR OBTAINED OR TRANSACTIONS
            ENTERED INTO THROUGH THE WEBSITE; OR (4) ANY LOST PROFITS YOU
            ALLEGE.
          </p>
          <p className="mb-5 leading-relaxed">
            SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF
            LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE
            ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            V. INDEMNIFICATION
          </p>
          <p className="mb-5 leading-relaxed">
            You will release, indemnify, defend and hold harmless BigIndia.com,
            and any of its contractors, agents, employees, officers, directors,
            shareholders, affiliates and assigns from all liabilities, claims,
            damages, costs and expenses, including reasonable attorneys' fees
            and expenses, of third parties relating to or arising out of (1)
            this Agreement or the breach of your warranties, representations and
            obligations under this Agreement; (2) the Website content or your
            use of the Website content; (3) the Products or your use of the
            Products (including Trial Products); (4) any intellectual property
            or other proprietary right of any person or entity; (5) your
            violation of any provision of this Agreement; or (6) any information
            or data you supplied to BigIndia.com. When BigIndia.com is
            threatened with suit or sued by a third party, BigIndia.com may seek
            written assurances from you concerning your promise to indemnify
            BigIndia.com; your failure to provide such assurances may be
            considered by BigIndia.com to be a material breach of this
            Agreement. BigIndia.com will have the right to participate in any
            defense by you of a third-party claim related to your use of any of
            the Website content or Products, with counsel of BigIndia.com choice
            at its expense. BigIndia.com will reasonably cooperate in any
            defense by you of a third-party claim at your request and expense.
            You will have sole responsibility to defend BigIndia.com against any
            claim, but you must receive BigIndia.com prior written consent
            regarding any related settlement. The terms of this provision will
            survive any termination or cancellation of this Agreement or your
            use of the Website or Products.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            VI. PRIVACY
          </p>
          <p className="mb-5 leading-relaxed">
            BigIndia.com believes strongly in protecting user privacy and
            providing you with notice of use of data. Please refer to
            BigIndia.com privacy policy, incorporated by reference herein, that
            is posted on the Website.
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            VI. AGREEMENT TO BE BOUND
          </p>
          <p className="mb-5 leading-relaxed">
            By using this Website or ordering Products, you acknowledge that you
            have read and agree to be bound by this Agreement and all terms and
            conditions on this Website.{" "}
          </p>
          <p className="mb-5 leading-relaxed text-xl font-semibold">
            VIII. GENERAL
          </p>
          <p className="mb-5 leading-relaxed">
            Force Majeure <br />
            BigIndia.com will not be deemed in default hereunder or held
            responsible for any cessation, interruption or delay in the
            performance of its obligations hereunder due to earthquake, flood,
            fire, storm, natural disaster, act of God, war, terrorism, armed
            conflict, labor strike, lockout, or boycott.
          </p>
          <p className="mb-5 leading-relaxed">
            Cessation of Operation
            <br />
            BigIndia.com may at any time, in its sole discretion and without
            advance notice to you, cease operation of the Website and
            distribution of the Products.
          </p>
          <p className="mb-5 leading-relaxed">
            Entire Agreement
            <br />
            This Agreement comprises the entire agreement between you and
            BigIndia.com and supersedes any prior agreements pertaining to the
            subject matter contained herein.
          </p>
          <p className="mb-5 leading-relaxed">
            Effect of Waiver
            <br />
            The failure of BigIndia.com to exercise or enforce any right or
            provision of this Agreement will not constitute a waiver of such
            right or provision. If any provision of this Agreement is found by a
            court of competent jurisdiction to be invalid, the parties
            nevertheless agree that the court should endeavor to give effect to
            the parties' intentions as reflected in the provision, and the other
            provisions of this Agreement remain in full force and effect.
          </p>
          <p className="mb-5 leading-relaxed">
            Governing Law; Jurisdiction
            <br />
            This Website originates from Delhi, India. This Agreement will be
            governed by the laws of India without regard to its conflict of law
            principles to the contrary. Neither you nor BigIndia.com will
            commence or prosecute any suit, proceeding or claim to enforce the
            provisions of this Agreement, to recover damages for breach of or
            default of this Agreement, or otherwise arising under or by reason
            of this Agreement, other than in courts located in Delhi. By using
            this Website or ordering Products, you consent to the jurisdiction
            and venue of such courts in connection with any action, suit,
            proceeding or claim arising under or by reason of this Agreement.
            You hereby waive any right to trial by jury arising out of this
            Agreement and any related documents.
          </p>
          <p className="mb-5 leading-relaxed">
            Statute of Limitation
            <br />
            You agree that regardless of any statute or law to the contrary, any
            claim or cause of action arising out of or related to use of the
            Website or Products or this Agreement must be filed within one (1)
            year after such claim or cause of action arose or be forever barred.
          </p>
          <p className="mb-5 leading-relaxed">
            Waiver of Class Action Rights
            <br />
            BY ENTERING INTO THIS AGREEMENT, YOU HEREBY IRREVOCABLY WAIVE ANY
            RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH THOSE OF OTHER IN THE FORM OF
            A CLASS ACTION OR SIMILAR PROCEDURAL DEVICE. ANY CLAIMS ARISING OUT
            OF, RELATING TO, OR CONNECTION WITH THIS AGREEMENT MUST BE ASSERTED
            INDIVIDUALLY.
          </p>
          <p className="mb-5 leading-relaxed">
            Termination
            <br />
            BigIndia.com reserves the right to terminate your access to the
            Website if it reasonably believes, in its sole discretion, that you
            have breached any of the terms and conditions of this Agreement.
            Following termination, you will not be permitted to use the Website
            and BigIndia.com may, in its sole discretion and without advance
            notice to you, cancel any outstanding orders for Products. If your
            access to the Website is terminated, BigIndia.com reserves the right
            to exercise whatever means it deems necessary to prevent
            unauthorized access of the Website. This Agreement will survive
            indefinitely unless and until BigIndia.com chooses, in its sole
            discretion and without advance to you, to terminate it.
          </p>
          <p className="mb-5 leading-relaxed">
            Domestic Use
            <br />
            BigIndia.com makes no representation that the Website or Products
            are appropriate or available for use in locations outside India.
            Users who access the Website from outside India do so at their own
            risk and initiative and must bear all responsibility for compliance
            with any applicable local laws.
          </p>
          <p className="mb-5 leading-relaxed">
            Assignment
            <br />
            You may not assign your rights and obligations under this Agreement
            to anyone. BigIndia.com may assign its rights and obligations under
            this Agreement in its sole discretion and without advance notice to
            you.
          </p>
          <p className="mb-5 leading-relaxed">
            BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU
            AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS
            AGREEMENT.
          </p>
        </div>
        <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
        <StaticImage
                src="../images/terms.terms"
                width={1000}
                alt="Buy and Sell with Bigindia"
                placeholder="tracedSVG"
                quality="40"
              />
        </div>
      </div>
    </div>
  </Layout>
)

export default Terms
